### ISSUE TITLE
Create "How It Works" Section from Figma Design

### ISSUE THREAD

**Issue by Oyinbrakemigrace** [world-wide-techies/annon_chat#5]
**Description**
The objective of this issue is to create the "How It Works" section for the landing page. The "How It Works" section will provide users with a clear and concise explanation of the process or steps involved in using the platform.

**Visual Reference**
![How It Works](https://github.com/world-wide-techies/annon_chat/assets/117949160/9c57b8df-b139-43d2-8491-fc4813747566)

**Comment by edidee** [comment]
I'll work on this
